### ISSUE TITLE
Add a license. 

### ISSUE THREAD

**Issue by rizwan2000rm** [codeforcauseorg/causefolio#10]
Add an MIT license to the project.

Also please let the first time contributors take this issue.
If you need help to add a license [refer this](https://choosealicense.com/licenses/mit/)

**Comment by AdityaTeltia** [comment]
I would like to take this issue ! haven't done this before but will learn by trying !

**Comment by rizwan2000rm** [comment]
@AdityaTeltia Go ahead! It is very easy, you just have to add a license file to root of project.
Fork the repo make the changes and submit a pr referencing this issue.
You can refer the link provided above for help.

**Comment by Abhishek-kumar09** [comment]
Merged in #11
