### ISSUE TITLE
Problems in Profile and drawers

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/causefolio#107]
The padding is required here:
The scrollbars on drawers are not a good thing.
![image](https://user-images.githubusercontent.com/48255244/124000560-574de300-d9f1-11eb-9a08-13e116ade667.png)

Go to causefolio.in and checkout to public profile. It is not visible;
 console errors:
![Screenshot from 2021-06-30 22-32-32](https://user-images.githubusercontent.com/48255244/124002247-2078cc80-d9f3-11eb-8a7f-d3cf1f7629e6.png)

origin: https://github.com/codeforcauseorg/causefolio/pull/106

**Comment by Abhishek-kumar09** [comment]
@dipscoder

**Comment by dipscoder** [comment]
Ok I will check this
