### ISSUE TITLE
[Frontend] Create navigation component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#21]
# Description

Refer the ui design and create the navigation component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/109629237-a3833680-7b69-11eb-866d-1ceeb8d11349.png)

# Colours

![image](https://user-images.githubusercontent.com/53532851/108118131-eb16b680-70c3-11eb-8c69-cc61f1d978cc.png)
![image](https://user-images.githubusercontent.com/53532851/109629899-56539480-7b6a-11eb-8fc9-b76a3014d258.png)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by Abhishek-kumar09** [comment]
You can use permanent drawer to implement is easily: https://material-ui.com/components/drawers/#permanent-drawer

This issue only require you to make a drawer and style it according to the view posted.

**Comment by rizwan2000rm** [comment]
Should I go ahead with the issue or someone else  want to take it ?

**Comment by AdityaTeltia** [comment]
Can I  work on this if @rizwan2000rm you have no problem 😅

**Comment by rizwan2000rm** [comment]
Sure go ahead. I have no issues at all.

**Comment by AdityaTeltia** [comment]
I just have to create this navigation component right ? Or I have to return it also somewhere ?

**Comment by Abhishek-kumar09** [comment]
You have to create a new route and a new page inside it you have to make this component.

**Comment by AdityaTeltia** [comment]
I am not that aware how to route , but will try and look up to it

**Comment by AdityaTeltia** [comment]
![component](https://user-images.githubusercontent.com/67232537/109926903-837a8100-7ce9-11eb-8f1d-782030519cdb.JPG)
As of now I have created a component in ```src/component``` with the name Navigation.js and designed this there . I know some designing part is remaining . @Abhishek-kumar09 @SHITIZ-AGGARWAL

**Comment by AdityaTeltia** [comment]
![localhost_3000_ (1)](https://user-images.githubusercontent.com/67232537/109933621-a4df6b00-7cf1-11eb-9269-15712a389113.png)
This is how the component looks !

**Comment by Abhishek-kumar09** [comment]
Create a PR, we will discuss further details there.
Also, the unselcted ones should have some faint texture than selected ones, are u facing some problem implementing that?

**Comment by AdityaTeltia** [comment]
Yes , actually as I am mapping through all the elements instead of creating individual element as In that case I would have given active className  to the one which is activated but I don't know how to do conditional rendering while mapping .

**Comment by AdityaTeltia** [comment]
@Abhishek-kumar09 We can close this issue !
