### ISSUE TITLE
[Frontend] Create the header component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#22]
# Description

### Refer the ui design and create the header component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/109918502-1103a400-7cdd-11eb-87e2-8f34659cd568.png)

![image](https://user-images.githubusercontent.com/53532851/109918939-d4847800-7cdd-11eb-9d40-7ed0cde4597f.png)

# Colours

![image](https://user-images.githubusercontent.com/53532851/109918696-6cce2d00-7cdd-11eb-8423-eec290837bda.png)

# Logo
[Logo1.svg.zip](https://github.com/codeforcauseorg/causefolio/files/6081196/Logo1.svg.zip)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by shrutixyz** [comment]
I'd like to do this

**Comment by AdityaTeltia** [comment]
@Abhishek-kumar09 @SHITIZ-AGGARWAL We can close this issue now !
