### ISSUE TITLE
[Frontend] Create the Calendar component for Dashboard

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#23]
# Description

### Refer the ui design and create the calendar component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/109919271-68eeda80-7cde-11eb-919d-033e4db19259.png)

![image](https://user-images.githubusercontent.com/53532851/109918939-d4847800-7cdd-11eb-9d40-7ed0cde4597f.png)

# Colours and Information

![image](https://user-images.githubusercontent.com/53532851/109919520-c84cea80-7cde-11eb-8ed0-915da1766264.png)
![image](https://user-images.githubusercontent.com/53532851/109919430-a3f10e00-7cde-11eb-8464-b213728d8c68.png)

![image](https://user-images.githubusercontent.com/53532851/109919923-84a6b080-7cdf-11eb-93c7-f6aaef12266a.png)

# Illustration Used
[round.svg.zip](https://github.com/codeforcauseorg/causefolio/files/6081246/round.svg.zip)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by piall** [comment]
I would like to work on that. Could I start work after few days?. I have exams.

**Comment by SHITIZ-AGGARWAL** [comment]
sure no problem

**Comment by AdityaTeltia** [comment]
Anyone working on this ? Or can I work ?

**Comment by piall** [comment]
> Anyone working on this ? Or can I work ?

I would like to work on that. I have not started working because of ongoing exam. I will start from 9 march.

**Comment by mdPial** [comment]
Could anyone give me resources? How to show a calendar monthly like the given UI in material UI?.

**Comment by piall** [comment]
@SHITIZ-AGGARWAL Could you assign me now?. I have already started working.

**Comment by piall** [comment]
Will the component show calendar just for one month (based on current month) only?

**Comment by Abhishek-kumar09** [comment]
Yes, we can start with that.
