### ISSUE TITLE
[Frontend] Create the stats component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#24]
# Description

### Refer the ui design and create the stats component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/109925913-57123500-7ce8-11eb-9961-dd47eb4f7192.png)
![image](https://user-images.githubusercontent.com/53532851/109918939-d4847800-7cdd-11eb-9d40-7ed0cde4597f.png)

# Colours and Information
![image](https://user-images.githubusercontent.com/53532851/109926057-845ee300-7ce8-11eb-9f3f-6ff0213cbf3a.png)
# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by AdityaTeltia** [comment]
I would like to work on this !
