### ISSUE TITLE
[Frontend] Create the bookmarked events component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#25]
# Description

### Refer the ui design and create the bookmarked events component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/109927874-d4d74000-7cea-11eb-8ab6-52876892d99c.png)

![image](https://user-images.githubusercontent.com/53532851/109927935-e91b3d00-7cea-11eb-9682-5920ed70f66d.png)

# Colours and Information

![image](https://user-images.githubusercontent.com/53532851/109927162-c9cfe000-7ce9-11eb-94ce-6e6758e3cf0a.png)
![image](https://user-images.githubusercontent.com/53532851/109927192-d7856580-7ce9-11eb-9d62-393a6004f0b4.png)

# Sample photo Used

![image](https://user-images.githubusercontent.com/53532851/109927313-04397d00-7cea-11eb-8c20-2046a4bb4832.png)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by shrutixyz** [comment]
I'm interested in working on this!

**Comment by shrutixyz** [comment]
On what route is this component being rendered?

**Comment by Abhishek-kumar09** [comment]
@shrutigupta5555 The component is prepared the route setup is required though.
https://github.com/codeforcauseorg/causefolio/issues/36

You can add route if you want.

**Comment by shrutixyz** [comment]
Okay I'll add the route. Thank you.
