### ISSUE TITLE
[Frontend] Create the new events component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#26]
# Description

### Refer the ui design and create the new events component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/109927642-888c0000-7cea-11eb-838b-e489c950b1f5.png)

![image](https://user-images.githubusercontent.com/53532851/109928217-3d262180-7ceb-11eb-8cb5-76f458d94e9a.png)

# Colours and Information

![image](https://user-images.githubusercontent.com/53532851/109919520-c84cea80-7cde-11eb-8ed0-915da1766264.png)
![image](https://user-images.githubusercontent.com/53532851/109919430-a3f10e00-7cde-11eb-8464-b213728d8c68.png)

![image](https://user-images.githubusercontent.com/53532851/109919923-84a6b080-7cdf-11eb-93c7-f6aaef12266a.png)

# Illustration Used

[Placeholder Alt..svg.zip](https://github.com/codeforcauseorg/causefolio/files/6081695/Placeholder.Alt.svg.zip)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by PranavDherange** [comment]
Can u assign this issue to me. I'm willing to work on it

**Comment by PranavDherange** [comment]
can anyone specify the dimensions of the events box..?

**Comment by PranavDherange** [comment]
can anyone assign me this issue asap

**Comment by naveen8801** [comment]
Hii @SHITIZ-AGGARWAL  , i wanna work on it , can you assign it to me ?

**Comment by mohitgupta1539** [comment]
Can i work on this issue

**Comment by oneknucklehead** [comment]
Is this issue still up for grab? If yes, can I work on this?

**Comment by zeborg** [comment]
Hey @Abhishek-kumar09, can I be assigned to this as well as the `bookmarked events` component issue? I finished working on these during my attempt to learn React components while working on this project and would really appreciate it if I'm allowed to make a single PR for both of these components along with the `publications` one which I was originally assigned and have completed as well 🙏

Here's the final output of my work on these components:
![image](https://user-images.githubusercontent.com/37282098/114677318-cfc4d200-9d27-11eb-9871-600e93ec62fb.png)

**Comment by zeborg** [comment]
Hey @Abhishek-kumar09
This issue can be closed now~
