### ISSUE TITLE
[Frontend] Create the publications component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#27]
# Description

### Refer the ui design and create the publications component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/109928750-c6d5ef00-7ceb-11eb-9dce-e66acbdf3fbd.png)

![image](https://user-images.githubusercontent.com/53532851/109927935-e91b3d00-7cea-11eb-9682-5920ed70f66d.png)

# Colours and Information

![image](https://user-images.githubusercontent.com/53532851/109927162-c9cfe000-7ce9-11eb-94ce-6e6758e3cf0a.png)
![image](https://user-images.githubusercontent.com/53532851/109927192-d7856580-7ce9-11eb-9d62-393a6004f0b4.png)

# Illustration used

[banner.svg.zip](https://github.com/codeforcauseorg/causefolio/files/6081715/banner.svg.zip)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by PranavDherange** [comment]
can you assign this issue to me? I'm willing to work on it

**Comment by Blastoise** [comment]
@P-star-art Can I take this issue? You can take the New Events Component?

**Comment by PranavDherange** [comment]
> @P-star-art Can I take this issue? You can take the New Events Component?

okay sure go ahead ;)

**Comment by Blastoise** [comment]
@P-star-art Thanks 😅

**Comment by mindninjaX** [comment]
Is this issue assigned? If not, I would like to weigh in...

**Comment by Blastoise** [comment]
@SHITIZ-AGGARWAL Can you specify the dimensions of the individual boxes? Also, it will be a stateless component receiving data using props?

**Comment by kaiwalyakoparkar** [comment]
I would like to work on this issue

**Comment by sg23600** [comment]
I would like to work on this issue

**Comment by adarsh-technocrat** [comment]
Hello @Abhishek-kumar09, @SHITIZ-AGGARWAL   is someone who is working on other sections like one event, blog, settings,?
if not I would love to work on these sections :)

**Comment by zeborg** [comment]
@adarsh-technocrat I've already been working on the Settings section, and will be finishing it soon following some related discussions with @SHITIZ-AGGARWAL. Other than that, you may ask @SHITIZ-AGGARWAL if any help is needed with the other sections :)

**Comment by adarsh-technocrat** [comment]
> @adarsh-technocrat I've already been working on the Settings section, and will be finishing it soon following some related discussions with @SHITIZ-AGGARWAL. Other than that, you may ask @SHITIZ-AGGARWAL if any help is needed with the other sections :)

Sure @zeborg  :)

 @Abhishek-kumar09, @SHITIZ-AGGARWAL  ping!
