### ISSUE TITLE
[Frontend] Create the profile info component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#33]
# Description

### Refer the ui design and create the profile info component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/110826398-0c318800-82bb-11eb-8437-cd67150e7723.png)

-----
![Profile page](https://user-images.githubusercontent.com/53532851/110826537-2cf9dd80-82bb-11eb-9ac1-f7494bca8085.png)

# Colours and Information

![image](https://user-images.githubusercontent.com/53532851/110827187-d640d380-82bb-11eb-8af1-75819345b5e6.png)

# Illustration used

[untitled folder.zip](https://github.com/codeforcauseorg/causefolio/files/6124777/untitled.folder.zip)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by AdityaTeltia** [comment]
I would like to work on this issue @SHITIZ-AGGARWAL

**Comment by AdityaTeltia** [comment]
@SHITIZ-AGGARWAL  Sorry but currently my endsem is going on so I have no time to work on this ! If this is required you can assign it to someone else otherwise I will start working on it after 27 .

**Comment by rockingrohit9639** [comment]
Can I work on it?

**Comment by AdityaTeltia** [comment]
Now I am starting working on it !

**Comment by Abhishek-kumar09** [comment]
@AdityaTeltia Are you working on it?

**Comment by AdityaTeltia** [comment]
Really sorry for the delay ! I am currently unwell if someone wants to take this can go on @Abhishek-kumar09

**Comment by nishant-rajput** [comment]
Hey, I would like to work on this issue.

**Comment by Abhishek-kumar09** [comment]
Go on @nishant-rajput

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 I would  like  to work on issue

**Comment by Abhishek-kumar09** [comment]
You have to create info component in your PR. Let's work on one component at a time :)

**Comment by Abhishek-kumar09** [comment]
@nishant-rajput Is there any update on it

**Comment by nishant-rajput** [comment]
@Abhishek-kumar09  been working on it. Currently, I am facing some issues using CSS and Grid component. Need some help with it.

It currently looks like this -

![Screenshot from 2021-05-21 12-59-41](https://user-images.githubusercontent.com/37553710/119246130-9a1fce00-bb9c-11eb-9088-33fdcbc9cb5f.png)

**Comment by ayushsom1** [comment]
Use CSS Flexbox Layout Module.

https://css-tricks.com/snippets/css/a-guide-to-flexbox/

https://reactnative.dev/docs/flexbox

**Comment by Abhishek-kumar09** [comment]
@nishant-rajput  Create a draft pull request where I can see your code.
