### ISSUE TITLE
[Frontend] Create the monthly commits component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#34]
# Description

### Refer the ui design and create the monthly commits component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/110827956-929a9980-82bc-11eb-862d-4b1764c65c80.png)

-----
![Profile page](https://user-images.githubusercontent.com/53532851/110826537-2cf9dd80-82bb-11eb-9ac1-f7494bca8085.png)

# Colours and Information

![image](https://user-images.githubusercontent.com/53532851/110828092-b5c54900-82bc-11eb-8378-bb0837ab2bd7.png)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by indevi** [comment]
I m a beginner to this project   and I would like to proceed with this issue. Can I be assigned the same

**Comment by kaiwalyakoparkar** [comment]
I would like to work on this issue

**Comment by Abhishek-kumar09** [comment]
@ShivamTyagi12345 Are you working on it?

**Comment by indevi** [comment]
> @ShivamTyagi12345 Are you working on it?
> Actually, one of my close ones is tested Covid Positive . Is it okay if I ask for a weeks time from now?

**Comment by Abhishek-kumar09** [comment]
It's Okay, take care
