### ISSUE TITLE
[Frontend] Create the badges component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#35]
# Description

### Refer the ui design and create the badges component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/110828372-fb821180-82bc-11eb-80bb-ae0679fc8523.png)

-----
![Profile page](https://user-images.githubusercontent.com/53532851/110826537-2cf9dd80-82bb-11eb-9ac1-f7494bca8085.png)

# Colours and Information

![image](https://user-images.githubusercontent.com/53532851/110828617-3b48f900-82bd-11eb-8d4f-9e5a35147635.png)

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

**Comment by piall** [comment]
I would like to work on that.
