### ISSUE TITLE
Setup Navigation round

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/causefolio#36]
In PR https://github.com/codeforcauseorg/causefolio/pull/28, @AdityaTeltia has created main component but had not setup the route.

Required: Setup route that points to the component made in https://github.com/codeforcauseorg/causefolio/pull/28

**Comment by Shashank024** [comment]
I would like to work on this @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
Please go on.
