### ISSUE TITLE
Dynamically update contributors in readme.md

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/causefolio#45]
**What is your feature request related to ?**

- [x] Docs

**What is your feature request? Describe**

Currently in the readme.md user needs to add himself/herself as a contributor after every y contribution, instead of this, we can easily add Dynamic link to auto-update contributors in the readme.

**Describe the solution you'd like**

Add required links
for ex: <a href="https://github.com/codeforcauseorg/causefolio/graphs/contributors"> </a> for changing image positions according to commits.

And for image you can use this <img src="https://contrib.rocks/image?repo=codeforcauseorg/causefolio" />

**Comment by Abhishek-kumar09** [comment]
Yes, it's good, but we have designers and other members who doesn't have code contribution but they contribute to it in more important ways.

**Comment by Abhijay007** [comment]
> Yes, it's good, but we have designers and other members who doesn't have code contribution but they contribute to it in more important ways.

ok, No problem 😀 I will close this issue.
