### ISSUE TITLE
Create event Form

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/causefolio#50]
Create Event form
![a](https://cdn.discordapp.com/attachments/845682486725705728/845885724489285642/Screenshot_2021-05-23-10-16-51-58.jpg)

**Comment by Amishakumari544** [comment]
I am working on it.

**Comment by Shashankmallibhat** [comment]
Do  we just need to do front end part?
And do we need to do it with html and css pages or through react?

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 Can i work on it

**Comment by mohit200008** [comment]
can i work on it ?

**Comment by Abhishek-kumar09** [comment]
This is fixed in https://github.com/codeforcauseorg/causefolio/pull/63

**Comment by Abhishek-kumar09** [comment]
@mohit200008 There are lots of bigger and smaller issues in the code you can find by setting up local development and running the project. You can create your own issue and come up with your PR.

**Comment by mohit200008** [comment]
I want to be a part of your community and learn from you.
