### ISSUE TITLE
Badges for Leaders

### ISSUE THREAD

**Issue by unnati914** [codeforcauseorg/causefolio#52]
**What is your feature request related to ?**

- [ ] Design (please specify i.e. Design, Testing etc)

**What is your feature request ? Describe**
A  batch for a particular leader on the basis of the events they do in their college such as bronze, silver,gold.
Bronze- 2+ events
Silver - 4 + events
Gold - 10+ events

![image](https://user-images.githubusercontent.com/69121168/119454959-fd6d4580-bced-11eb-9098-e02cf44c12ba.png)
The design will be like this with color variations

**Comment by kanup** [comment]
We just have to create a design like on illustrator or something?

**Comment by unnati914** [comment]
Done with the issue kindly review it please
