### ISSUE TITLE
[Frontend] Create Landing Page(2nd part)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#6]
# Description

Refer the ui design and create the landing page(2)

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/108118248-126d8380-70c4-11eb-8d37-675729b20c3c.png)

# Colours

![image](https://user-images.githubusercontent.com/53532851/108118131-eb16b680-70c3-11eb-8c69-cc61f1d978cc.png)
![image](https://user-images.githubusercontent.com/53532851/108118175-fa95ff80-70c3-11eb-862c-22fed7a7d589.png)

# illustrations

[Archive.zip](https://github.com/codeforcauseorg/causefolio/files/5991518/Archive.zip)

**Comment by AdityaTeltia** [comment]
I can try working on this ! Just wanted to know is navbar created ? if not then where can I get the image of logo and is causefolio simple text or that is an svg too ?

**Comment by SHITIZ-AGGARWAL** [comment]
@AdityaTeltia Go ahead 👍 , No Navbar is not created. Here is the logo and text as svg - 
[Logo.svg.zip](https://github.com/codeforcauseorg/causefolio/files/5994271/Logo.svg.zip)

**Comment by AdityaTeltia** [comment]
Ok ! I will try making as I have just recently learned react .

**Comment by AdityaTeltia** [comment]
One more doubt , How should I do the styling means inline styling or seperate css file in assets by adding className or can I do any of that ?

**Comment by Abhishek-kumar09** [comment]
@AdityaTeltia how to do styling?

We are using material-ui: https://material-ui.com/

This is the code example of how it works: https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/components/AboutCard/MainCard.js

If you are feeling that it overloaded, you can use css too that should not be the hinderance at all.
Just these things makes styling much easier and much consistent.

**Comment by Abhishek-kumar09** [comment]
Also, the material-ui documentation is one of the best documentatioin I know, so you have to just search for the component you are gonna make and you will get an already implemented component for that.

**Comment by AdityaTeltia** [comment]
Oh ok thankyou I'll definitely look up to it .

**Comment by thealoneshadow** [comment]
Can I work on the landing Page?

**Comment by Abhishek-kumar09** [comment]
@AdityaTeltia is already working on this.

**Comment by Abhishek-kumar09** [comment]
@thealoneshadow  We will be opening some new issues once design for new pages are finalized. I will tag you there or you can pick them.

**Comment by thealoneshadow** [comment]
> @thealoneshadow We will be opening some new issues once the design for new pages are finalized. I will tag you there or you can pick them.

It would be great. I am Divyanshu Goyal CFC lead.

**Comment by AdityaTeltia** [comment]
@Abhishek-kumar09 Can we close this issue now ?
