### ISSUE TITLE
[Frontend] Create Login component

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [codeforcauseorg/causefolio#7]
# Description

Refer the ui design and create the Login component

# Screenshot

![image](https://user-images.githubusercontent.com/53532851/108119123-5ad97100-70c5-11eb-8d47-b8625f040c84.png)

# Colours

![image](https://user-images.githubusercontent.com/53532851/108118131-eb16b680-70c3-11eb-8c69-cc61f1d978cc.png)
![image](https://user-images.githubusercontent.com/53532851/108118175-fa95ff80-70c3-11eb-862c-22fed7a7d589.png)
![image](https://user-images.githubusercontent.com/53532851/108119371-b277dc80-70c5-11eb-8cce-fa511df88b74.png)
 ### Login button : Gradient - 5731BA and 291757

# link

For reference you can see the design prototype : 
https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Untitled?node-id=9%3A48&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

# illustrations

![image](https://user-images.githubusercontent.com/53532851/108119831-5b263c00-70c6-11eb-8f64-7e414b19440a.png)

**Comment by piall** [comment]
Hello, I would like to work on this issue!

**Comment by SHITIZ-AGGARWAL** [comment]
Sure you can start working 👍

**Comment by piall** [comment]
![image](https://user-images.githubusercontent.com/43095489/108345020-fecb3580-7207-11eb-8a58-459b79c69d1a.png)
Do I have to integrate login component here for now? I am little confused as the main page is not ready

**Comment by SHITIZ-AGGARWAL** [comment]
> ![image](https://user-images.githubusercontent.com/43095489/108345020-fecb3580-7207-11eb-8a58-459b79c69d1a.png)
> Do I have to integrate login component here for now? I am little confused as the main page is not ready

No you can just make the login component for now

**Comment by piall** [comment]
I have some questions. What will be the font size of input box also  the space between text (inside input box) and input box border?

**Comment by Abhishek-kumar09** [comment]
> I have some question

for now you can refer to this: https://www.figma.com/proto/dMw9GAeJja2baVhDoceAEB/Causefolio?node-id=9%3A0&viewport=-1544%2C148%2C0.4358828365802765&scaling=contain

Font Size bold: color: `#3291755, 100%
![image](https://user-images.githubusercontent.com/48255244/108683724-01839e80-7518-11eb-9054-00c2e3d84ad4.png)

Normal: 
![image](https://user-images.githubusercontent.com/48255244/108683849-2aa42f00-7518-11eb-8abc-a04f6aa86637.png)
