### ISSUE TITLE
Create Footer: 

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/causefolio#77]
![image](https://user-images.githubusercontent.com/48255244/121184419-b00edd80-c882-11eb-921c-ca656919a62a.png)
Create Footer component

**Comment by harkiratsm** [comment]
**I would work on this **🚀****

**Comment by harkiratsm** [comment]
fix #78

**Comment by meenaljain0303** [comment]
I would like to work on this issue
