### ISSUE TITLE
Create a Pull Request Template

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/causefolio#8]
Create a pull request template.
Template should contain:
- Ran `npm run format`?
- Does it solve the problem?
- ...

UI:
- Is it responsive?
- Does it replicate the design?
- ...

New Feature:
- Summary of the feature
- Does it break the existing the feature?
- ...

You can add more checks, these are just that came into my mind at the moment.

**Comment by devkapilbansal** [comment]
Hi @Abhishek-kumar09 I would like to take this
