### ISSUE TITLE
Add a smooth page transition from going from homepage to second page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/causefolio#87]
Landing page 
| landing page | second page | 
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/48255244/121801247-03eb3f00-cc54-11eb-81ef-0ed7f137210c.png) |  ![image](https://user-images.githubusercontent.com/48255244/121801291-40b73600-cc54-11eb-8827-3491e648e38e.png) |

There should be a smooth transition where we go from the landing page to second page, with the wave moving upward

**Comment by Shashankmallibhat** [comment]
I would like to work on this  @Abhishek-kumar09 please assign me

**Comment by Shashankmallibhat** [comment]
https://user-images.githubusercontent.com/78919621/121876086-c73c4800-cd26-11eb-8eee-e78a80ed31ed.mp4

@Abhishek-kumar09 bhaiya can that wave svg be fixed to landing page so that i can try for smooth scrolling or will that wave be like that only?

**Comment by Abhishek-kumar09** [comment]
Yes, it can be fixed to landing page, maybe the position is set to `fixed` or `absolute` that's why this behaviour is seen.
Have to change that position to relative so that it get scrolled up.

**Comment by dipscoder** [comment]
You can refer to this video for the scroll effect: 
https://youtu.be/Nt70Ld0dJCM

**Comment by Shashankmallibhat** [comment]
Thank you for the help @dipscoder 😊
